=== ChristianG0816/xmlvalido_Grupo05/Ejercicios/dtd_externa/dtd/tareas.dtd
<!ELEMENT universidad (facultad)>
<!ELEMENT facultad (carrera)>
<!ELEMENT carrera (asignatura)>
<!ELEMENT asignatura (gt|gd|gl)+>
<!ELEMENT gt (grupos)>
<!ELEMENT gd (grupos)>
<!ELEMENT gl (grupos)>
<!ELEMENT grupos (equipo)+>
<!ELEMENT equipo (tema,evaluacion,integrantes)*>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT integrantes (cabecera,coordinador,integrante+)>
<!ELEMENT cabecera (carnet,apellido,nombre)>
<!ELEMENT coordinador (carnet,apellido,nombre)>
<!ELEMENT integrante (carnet,apellido,nombre)>
<!ELEMENT carnet (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT evaluacion (actividadEvaluada)+>
<!ELEMENT actividadEvaluada (#PCDATA)>

<!-- ATRIBUTOS -->
<!ATTLIST universidad nombre CDATA #FIXED "UNIVERSIDAD DE EL SALVADOR">
<!ATTLIST facultad codigo ID #REQUIRED>
<!ATTLIST facultad nombre CDATA #REQUIRED>
<!ATTLIST carrera codigo ID #REQUIRED>
<!ATTLIST carrera nombre CDATA #REQUIRED>
<!ATTLIST asignatura nombre CDATA #REQUIRED>
<!ATTLIST gd numero CDATA #REQUIRED>
<!ATTLIST gd profesor CDATA #REQUIRED>
<!ATTLIST gt numero CDATA #REQUIRED>
<!ATTLIST gt profesor CDATA #REQUIRED>
<!ATTLIST gl numero CDATA #REQUIRED>
<!ATTLIST gl profesor CDATA #REQUIRED>
<!ATTLIST equipo numero CDATA #REQUIRED>
<!ATTLIST coordinador sexo CDATA #REQUIRED>
<!ATTLIST actividadEvaluada porcentaje CDATA #REQUIRED>

=== ChristianG0816/xmlvalido_Grupo05/Ejercicios/dtd_externa/tareas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- Tarea GRUPO05 -->
<?xml-stylesheet type="text/css" href="../../css/tareas.css" ?>
<!DOCTYPE universidad SYSTEM "dtd/tareas.dtd">
<universidad>
<facultad ID="FIA" nombre="Ingenieria y Arquitectura">
<carrera ID="SI" nombre="Sistemas Informaticos">
    <asignatura nombre="Tecnicas de programacion para internet">
        <gt numero="5" profesor ="Ing. Balmore Ortiz">
            <grupos>
                <equipo numero="1">
                    <tema>Expresiones regulares</tema>
                    <evaluacion>
                    <actividadEvaluada porcentaje="25%">
                        Guia 36
                    </actividadEvaluada>
                    </evaluacion>
                    <integrantes>
                        <cabecera>
                            <carnet>CARNET</carnet>
                            <apellido>APELLIDO</apellido>
                            <nombre>NOMBRE</nombre>
                        </cabecera>
                        <coordinador sexo="F">
                            <carnet>PD78655</carnet>
                            <apellido>Pineda Delgado</apellido>
                            <nombre>Carolina Isabel</nombre>
                         </coordinador>
                        <integrante>
                           <carnet>PD78655</carnet>
                            <apellido>Pineda Delgado</apellido>
                            <nombre>José Gustavo</nombre>
                        </integrante>
                        <integrante>
                            <carnet>VM19003</carnet>
                            <apellido>Vásquez Mancia</apellido>
                            <nombre>William Enrique</nombre>
                        </integrante>
                        <integrante>
                            <carnet>AR15151</carnet>
                            <apellido>Amaya Rodriguez</apellido>
                            <nombre>Miguel Angel</nombre>
                            </integrante>
                    </integrantes>
                </equipo>
            </grupos>
        </gt>

        <gd numero="2" profesor ="Ing. Balmore Ortiz">
            <grupos>
                <equipo numero="1">
                    <tema>XML Valido</tema>
                    <evaluacion>
                    <actividadEvaluada porcentaje="25%">
                        Guia 32
                    </actividadEvaluada>
                    </evaluacion>
                    <integrantes>
                        <cabecera>
                            <carnet>CARNET</carnet>
                            <apellido>APELLIDO</apellido>
                            <nombre>NOMBRE</nombre>
                        </cabecera>
                        <coordinador>
                            <carnet>AR15151</carnet>
                            <apellido>Amaya Rodriguez</apellido>
                            <nombre>Miguel Angel</nombre>
                        </coordinador>
                        <integrante>
                            <carnet>AG45454</carnet>
                            <apellido>Ayala Guerra</apellido>
                            <nombre>Christian Javier</nombre>
                        </integrante>
                        <integrante>
                            <carnet>AG45454</carnet>
                            <apellido>Ayala Guerra</apellido>
                            <nombre>Diego José</nombre>
                        </integrante>
                        <integrante>
                            <carnet>CJ28569</carnet>
                            <apellido>Cornejo Jiménez</apellido>
                            <nombre>Cornejo Jiménez</nombre>
                        </integrante>
                    </integrantes>
                    
                </equipo>
            </grupos>
        </gd>

        <gl numero="2" profesor ="Ing. Balmore Ortiz">
            <grupos>
                <equipo numero="1">
                    <tema>XML bien formado</tema>
                    <evaluacion>
                    <actividadEvaluada porcentaje="25%">
                        Guia 31 b
                    </actividadEvaluada>
                    </evaluacion>
                    <integrantes>
                        <cabecera>
                            <carnet>CARNET</carnet>
                            <apellido>APELLIDO</apellido>
                            <nombre>NOMBRE</nombre>
                        </cabecera>
                        <coordinador>
                            <carnet>PD78655</carnet>
                            <apellido>Pineda Delgado</apellido>
                            <nombre>José Gustavo</nombre>
                        </coordinador>
                        <integrante>
                            <carnet>AG45454</carnet>
                            <apellido>Ayala Guerra</apellido>
                            <nombre>Diego José</nombre>
                        </integrante>
                        <integrante>
                            <carnet>VM19003</carnet>
                            <apellido>Vásquez Mancia</apellido>
                            <nombre>William Enrique</nombre>
                        </integrante>
                        <integrante>
                            <carnet>CJ28569</carnet>
                            <apellido>Cornejo Jiménez</apellido>
                            <nombre>Cornejo Jiménez</nombre>
                        </integrante>
                    </integrantes>
                    
                </equipo>
            </grupos>
        </gl>
    </asignatura>
</carrera>
</facultad>
</universidad>
